version: "3.8"
services:
  fastapi_todo_analytics_app:
    build: .
    container_name: ${WEB_HOST}
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    env_file:
      - .env
    entrypoint:
      - ./entrypoints/fastapi.sh

  localstack_app:
    image: localstack/localstack
    container_name: ${DB_HOST}
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - SERVICES=dynamodb
      - DEBUG=0
